name:                 Date-validator
# Build settings
markdown:             redcarpet
highlighter:          pygments
relative_permalinks:  false

source:               .
destination:          ../dateValidatorDocs
exclude:              ['node_modules', 'dist']
include:              ['.gitignore']
timezone:             Africa/Casablanca

# Site settings
title:                Date Validator
description:          A date validator for jquery-validation plugin.
keywords:             jquery, jquery-plugin, jquery-validate, jquery-validation, date, date validator, validation, validate
fullname:             Brahim Arkni
github_username:      Arkni
repository:
  source:             https://github.com/Arkni/date-validator
  download:
    tag_zip:          https://github.com/Arkni/date-validator/archive/v2.0.0.zip
    tag_tar:          https://github.com/Arkni/date-validator/archive/v2.0.0.tar.gz
